### ISSUE TITLE
Gatekeeper on macOS

### ISSUE THREAD

**Issue by icetee** [gingemonster/GameBoyPngConverter#4]
Apple has been using [Gatekeeper](https://support.apple.com/en-us/HT202491) since macOS Catalina (2019 october). Applications that are not signed must be separately enabled. This wouldn't even be a problem, but all use .dll's and .dylib's need to be enabled one by one. (So all in all.) Until all of them are enabled, one by one, it will not start.

I think a solution to this might be that if macOS is under construction portable. Then maybe only 1 should be allowed.

**Comment by gingemonster** [comment]
@icetee are you up for testing the new release before I put it out, i have hopefully compiled to a single file on all platforms

**Comment by gingemonster** [comment]
Hopefully solve by latest release but not way to test
